In [192]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!pip install package_name --user


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!python.exe -m pip install --upgrade pip

  Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:


ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'c:\\python311\\lib\\site-packages\\pip-23.1.2.dist-info\\AUTHORS.txt'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import numpy
num =  numpy.random.randint
print(num)

3


In [7]:
import numpy as np # np로 별칭 사용
num = np.random.randint(10) # 별칭을 이용해서 사용해야한다/
print(num)

4


In [13]:
# 1차원 배열
num1 = np.random.randint(10, size=6)
# 크기가 6인 1차원 배열
print(num1)

[0 5 9 7 7 9]


In [15]:
l =[0, 5, 9, 7, 7, 9]
print(l)#[0, 5, 9, 7, 7, 9] : 리스트
#          0 1  2  3  4  5 : index
print(num1)#[0 5 9 7 7 9]: 배열
# indexing
print(l[1])
print(num1[1])
print(l[4])
print(num1[4])
#slicing
print(l[2:4])
print(num1[2:4])

[0, 5, 9, 7, 7, 9]
[0 5 9 7 7 9]
5
5
7
7
[9, 7]
[9 7]


In [18]:
# 2차원 배열
num2 = np.random.randint(10, size=(2, 6))#2행 6열
print(num2)

[[8 2 7 2 6 6]
 [8 4 0 0 0 1]]


In [21]:
l2 = [[8, 2, 7, 2, 6, 6],[8, 4, 0, 0, 0, 1]]
#             0                   1:index
#      0  1  2  3  4  5   0  1  2  3  4  5:index
# 리스트를 포함하고 있는 리스트와 같다.
'''
[[8 2 7 2 6 6] 0행
 [8 4 0 0 0 1]] 1행
 [[8  2  7  2  6  6] [8  4  0  0  0  1]]
       0행           1행
   0열1열2열3열4열5열  0열1열2열3열4열5열
'''
print(l2)
print(num2)
print(l2[1][2])
print(num2[1][2])# 리스트 표현식
print(num2[1, 2])#행, 열 : 배열 표현식

[[8, 2, 7, 2, 6, 6], [8, 4, 0, 0, 0, 1]]
[[8 2 7 2 6 6]
 [8 4 0 0 0 1]]
0
0
0


In [36]:
#[0, 5, 9, 7, 7, 9]
# 0  1  2  3  4  5 : 리스트에서는 index
# -6 5  4  3  2  1
#[0  5  9  7  7  9]
# 0  1  2  3  4  5 : 배열에서는 열 이라고 부른다
# -6 5  4  3  2  1
print(l) #리스트
print(num1)# 1차원 배열
print(l[1])
print(num1[1])
print(l[-5])
print(num1[-5])
print(l[2:4])
print(num1[2:4])
print(l[-4:-2])
print(num1[-4:-2])
print(l[0:3])
print(l[:3])# 0 을 생략 할수 있다
print(num1[:3])
print(l[3:6])
print(l[3:]) # 마지막 번호는 생략 할수 있다
print(num1[3:])
# 전체를 한 개 씩 건너뛰어라
print(l[::2])
print(num1[::2])
print(l[::-1])
print(num1[::-1])
print(l[1])
l[1] = 10
print(l)
print(num1[1])
num1[1] = 10
print(num1)

[0, 5, 9, 7, 7, 9]
[0 5 9 7 7 9]
5
5
5
5
[9, 7]
[9 7]
[9, 7]
[9 7]
[0, 5, 9]
[0, 5, 9]
[0 5 9]
[7, 7, 9]
[7, 7, 9]
[7 7 9]
[0, 9, 7]
[0 9 7]
[9, 7, 7, 9, 5, 0]
[9 7 7 9 5 0]
5
[0, 10, 9, 7, 7, 9]
5
[ 0 10  9  7  7  9]


In [49]:
#[[8, 2, 7, 2, 6, 6], [8, 4, 0, 0, 0, 1]]
#        0index              1index
#       -2index             -1index
#  0  1  2  3  4  5    0  1  2  3  4  5 : index
# -6  5  4  3  2  1   -6  5  4  3  2  1  : index
#[[8  2  7  2  6  6][8  4  0  0  0  1]]
#        0행               1행
#       -2행              -1행
# 0열1열2열3열4열5열  0열1열2열3열4열5열
#-6열5열4열3열2열1열 -6열5열4열3열2열1열
print(l2)
print(num2)
print(l2[0][2])
print(num2[0][2])
print(num2[0,2])
#print(l2[0,2])
print('---------------------')
print(l2[-2][-4])
print(num2[-2][-4])
print(num2[-2,-4])

[[8, 2, 7, 2, 6, 6], [8, 4, 0, 0, 0, 1]]
[[8 2 7 2 6 6]
 [8 4 0 0 0 1]]
7
7
7
---------------------
7
7
7


In [51]:
num3 = np.random.randint(10,size=(3, 4))
print(num3)

[[0 6 3 8]
 [2 9 4 4]
 [3 1 8 0]]


In [52]:
l3 = [[0, 6, 3, 8],
      [2, 9, 4, 4],
      [3, 1, 8, 0]] 
print(l3)

[[0, 6, 3, 8], [2, 9, 4, 4], [3, 1, 8, 0]]


In [71]:
'''
리스트
  0  1  2  3index
[[0, 6, 3, 8],     #0index
 [2, 9, 4, 4],     #1index
 [3, 1, 8, 0]]     #2index
배열
  0 1 2 3열
[[0 6 3 8]         #0행
 [2 9 4 4]         #1행
 [3 1 8 0]]        #2행
 '''
print(l3[1])# 1index
print(num3[1])# 1행
print(l3[:][:3]) 
print(num3[:][:3])# 리스트 표현식 : 전체를 가지고 오는 것은 표현이 가능
print(num3[:,:3]) #배열 표현식    : 일부만 가지고 오는 표현이 가능
print(l3[:][::2])
print(num3[:][::2])
print(num3[:,::2]) # [행 , 열]
print('---------------------')
print(l3[::2][::2]) # l3[::2] 까지만 표현이 된다.
print(num3[::2][::2]) # [::2]
print(num3[::2,::2])
print(l3[:][::-1]) #[[3, 1, 8, 0], [2, 9, 4, 4], [0, 6, 3, 8]]
print(num3[:][::-1])#[[3 1 8 0][2 9 4 4][0 6 3 8]]
print(num3[:,::-1])#[[8 3 6 0][4 4 9 2][0 8 1 3]]
print(num3[::-1,:])#[[3 1 8 0] [2 9 4 4] [0 6 3 8]]
print(num3[::-1,::-1])#[[0 8 1 3] [4 4 9 2] [8 3 6 0]]

[2, 9, 4, 4]
[2 9 4 4]
[[0, 6, 3, 8], [2, 9, 4, 4], [3, 1, 8, 0]]
[[0 6 3 8]
 [2 9 4 4]
 [3 1 8 0]]
[[0 6 3]
 [2 9 4]
 [3 1 8]]
[[0, 6, 3, 8], [3, 1, 8, 0]]
[[0 6 3 8]
 [3 1 8 0]]
[[0 3]
 [2 4]
 [3 8]]
---------------------
[[0, 6, 3, 8]]
[[0 6 3 8]]
[[0 3]
 [3 8]]
[[3, 1, 8, 0], [2, 9, 4, 4], [0, 6, 3, 8]]
[[3 1 8 0]
 [2 9 4 4]
 [0 6 3 8]]
[[8 3 6 0]
 [4 4 9 2]
 [0 8 1 3]]
[[3 1 8 0]
 [2 9 4 4]
 [0 6 3 8]]
[[0 8 1 3]
 [4 4 9 2]
 [8 3 6 0]]


In [77]:
print(l3)
print(num3)
print(l3[0][1])
l3[0][1] = 40
print(l3)
print(num3[0][1])
num3[0][1]=40 #리스트 표현식 (가능하지만 사용을 자제)
print(num3)
num3[0,1]=400 # 배열 표현식
print(num3)

[[0, 40, 3, 8], [2, 9, 4, 4], [3, 1, 8, 0]]
[[ 0 40  3  8]
 [ 2  9  4  4]
 [ 3  1  8  0]]
40
[[0, 40, 3, 8], [2, 9, 4, 4], [3, 1, 8, 0]]
40
[[ 0 40  3  8]
 [ 2  9  4  4]
 [ 3  1  8  0]]
[[  0 400   3   8]
 [  2   9   4   4]
 [  3   1   8   0]]


In [79]:
### 배열을 만드는 방법
# 1.random을 이용하는 방법
num = np.random.randint(10,size =6) # 열의 집합  1차원 배열
print(num)
num = np.random.randint(10,size=(3, 4))#행,열 : 2차원배열
print(num)                                # 1차원의 집합체 : 1차원을 행이라고 하고
num = np.random.randint(10,size=(3,3, 4)) #면,행,열 : 3차원 배열
print(num)                                # 2차원의 집합 : 2차원을 면이라고 한다.

[1 5 4 2 8 4]
[[2 0 2 7]
 [6 5 5 8]
 [1 0 0 4]]
[[[6 9 7 1]
  [8 5 9 8]
  [2 9 3 0]]

 [[7 4 6 8]
  [3 6 7 3]
  [5 4 7 1]]

 [[6 4 3 8]
  [2 2 5 1]
  [9 5 9 1]]]


In [80]:
for num in range(10):# range함수는 파이썬
    print(num)

0
1
2
3
4
5
6
7
8
9


In [91]:
#2. arange()함수를 사용하는 방법:1차원
# arange함수는 numpy 에 있는 함수
#1차원 배열을 만들어 주는 함수
print(np.arange(10)) # [0 1 2 3 4 5 6 7 8 9]
m1 = np.arange(9)# 0부터 8까지값을 가지는 1차원 배열
print(m1)
m2 = np.arange(9).reshape(3,3) # 0~8까지 9개의 숫자로 이루어진 배열
print(m2)
#m2 = np.arange(9).reshape(3,4) # 9개의 숫자인데 12개를 만들어야 함으로 오류 발생
m3 = np.arange(12).reshape(3,4) # 0~8까지 9개의 숫자로 이루어진 배열
print(m3)
m4 = np.arange(11,11+12).reshape(3,4)
print(m4)
l4 = [1,2,3,4,5] # 2
print(l4[1])
l5 = [[1,2,3,4,5]] #
print(l5[0][1])
# 행이 한개인 2차원배열을 만들자
m5 = np.arange(1,4).reshape(1,3)
print(m5)
m6 = np.arange(1,4).reshape(3,1)
print(m6)
'''
[[1],
 [2],
 [3]]
'''
#m4 = np.arange(11, 11+12).reshape(3,4) # 3행 4열
m7 = np.arange(11,23) .reshape(4,3) # 4행 3열
print(m7)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
2
2
[[1 2 3]]
[[1]
 [2]
 [3]]
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [93]:
#3. array() 함수를 사용하는 방법 : 리스트, 튜플을 이용
m9 = np.array([1,2,3])
print(m9)
m10 = np.array((1,2,3))
print(m10)
# 리스트를 포함한 리스트나 튜플을 포함한 튜플을 이용해서 2차원 배열을 만든다
m11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m11)
m12 = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(m12)
m13 = np.array(((1,2,3),(4,5,6),(7,8,9)))
print(m13)
m14 = np.array(((1,2,3),(4,np.NaN,6),(7,8,np.NaN)))
print(m14)
# np.NaN을 결측치라고 한다. NaN은 Not a Numeber : 알수 없는 값을 의미, null과 같다.

[1 2 3]
[1 2 3]


In [95]:
l1 = [1,2,3]
l2 = [3,2,1]
result = l1 + l2 # 연결
print(result)
x = np.array([1,2,3])
y = np.array([3,2,1])
result = x + y # +:덧셈
print(result)

[1, 2, 3, 3, 2, 1]


In [101]:
# 배열을 확장하기
print(x)
print(y)
z = np.concatenate((x,y))
print(z)
v = [99,99,99]
z = np.concatenate((x,y,v))# 배열에 리스트나 튜플 배열로 연결이 된다.
print(z)
z = np.concatenate((x,y,v))# 배열에 리스트나 튜플 배열로 연결이 된다.
print(z)
z = np.concatenate(([1,2,3],(3,2,1),[99,99,99]))
print(z)
z = np.concatenate((l1,l2,v))
print(z)

[1 2 3]
[3 2 1]
[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[ 1  2  3  3  2  1 99 99 99]
[ 1  2  3  3  2  1 99 99 99]
[ 1  2  3  3  2  1 99 99 99]


In [107]:
#2차원배열 확장하기
x2 = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4],
                 [3,2,1]])
grid1 = np.array([[9,8,7],[6,5,4],[3,2,1]])
'''
[9,8,7],
[6,5,4],
[3,2,1]

z=np.concatenate((grid,x2), axis = 0) # 열기준, x축 기준
print(z)
concatenate를 사용하는 경우에는 차원이 같아야한다. 행과 열이 같다.
3행4열과 4행3열은 2차원이라는 것 같지만 차원은 다르다고 말한다.

z=np.concatenate((grid,x2), axis = 1) # 행기준, Y축 기준
print(z)
grid
[9,8,7],
[6,5,4],
[3,2,1]
grid1
[9,8,7],
[6,5,4],
[3,2,1]
'''
z= np.concatenate((grid,grid1), axis = 0)
print(z)
z= np.concatenate((grid,grid1))#axis=0은 기본값이 된다.
print(z)
z= np.concatenate((grid,grid1),axis=1 ) #axis=1 : 행기준 , y축 기준
print(z)

[[9 8 7]
 [6 5 4]
 [3 2 1]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]
 [9 8 7]
 [6 5 4]
 [3 2 1]]


In [112]:
# 차원이 다른 경우
print(x2)
print(grid)
z = np.vstack((x2,grid))# 열의 차원이 같고 행의 차원이 다른 경우
print(z)
#z = np.hstack((x2,grid))
grid2 = np.array([1,2],[9,8],[7,6])
print(grid2)
'''
[9 8 7] [1,2]
[6 5 4] [9,8]
[3 2 1] [7,6]
'''
z = np.hstack((grid1,grid2))#열의 차원은 달라도 행의 차원이 같은 경우
print(z)

[1 2 3]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]
 [9 8 7]
 [6 5 4]
 [3 2 1]]


TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [113]:
# 유니버설 함수(UFuncs)
l1 = [1,2,3]
l2 = [3,2,1]
x = np.array(l1)
y = np.array(l2)
result =  x + y
print(result)# [4 4 4]
result = l1 + l2
print(result)# [1, 2, 3, 3, 2, 1]

[4 4 4]
[1, 2, 3, 3, 2, 1]


In [114]:
def add(i,j):
    l4 = []
    for idx in range(len(i)):
        l4.append(i[idx]+j[idx])
        return l4

In [116]:
result = add(l1,l2)
print(result)

[4]


In [124]:
result = x + y 
print(result)
result = np.add(x,y)
print(result)
# + ,-, *, *,%,//,** 를 사용할 때 자동으로 실행되는 유니버셜 함수
# 비교연산자에 대한 유니버셜 함수도 있다.
result = x- y
print(result)
result = np.subtract(x,y)
print(result)
result = x*y
print(result)
result = np.multiply(x,y)
print(result)
result = x/y
print(result)
result = np.divide(x,y)
print(result)


[4 4 4]
[4 4 4]
[-2  0  2]
[-2  0  2]
[3 4 3]
[3 4 3]
[0.33333333 1.         3.        ]
[0.33333333 1.         3.        ]


In [195]:
# 브로드케스팅
print(x)
print(y)
# 배열을 연산하기 위해서는 차원이 같아야한다.
z = x+ 5 # 1차원배별 + 정수 :[1 2 3] + [5 5 5] : 정수가 3열짜리 1차원 배열이 되어야 한다.
# 서로 다른 차원을 가진 배열이 같은 차원으로 확장이 되는 것
print(z) # [6 7 8]
k = np.array([[1],[2],[3]])
print(k)
'''
[1 2 3] + [[1][1][1]
[1 2 3] +  [2][2][2]
[1 2 3] +  [3][3][3]]
'''
z = x + k
print(z)
'''
[1 2 3] + [[1][1][1]
[1 2 3] +  [2][2][2]
[1 2 3] +  [3][3][3]]
'''
print(grid)
z = grid + 5
print(z)

[[7 4 3 1 8 6]
 [8 5 9 0 2 1]
 [0 3 3 4 9 4]
 [1 0 6 0 4 5]]
[3 2 1]
[[12  9  8  6 13 11]
 [13 10 14  5  7  6]
 [ 5  8  8  9 14  9]
 [ 6  5 11  5  9 10]]
[[1]
 [2]
 [3]]


ValueError: operands could not be broadcast together with shapes (4,6) (3,1) 

In [129]:
#넘파이함수
# 제로행렬
m = np.zeros(3)
print(m)
m = np.zeros((3,3))
print(m)
# 원(1)행렬
m = np.ones(3)
print(m)
m = np.ones([3,3])
print(m)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [137]:
#집계함수
l = [1,2,3,4,5,6]
print(max(l)) # 내장함수
print(min(l))
print(sum(l))
m = np.random.randint(10, size = 6)
print(m)
print(sum(m))
print(np.sum(m))
print(m.sum())
print(np.sum(l))
#print(l.sum())
print(m.max())
print(np.max(m))
print(m.min())
print(np.min(m))

6
1
21
[3 6 9 5 2 7]
32
32
32
21
9
9
2
2


In [142]:
m = np.random.random((4,3))
print(m)
print(sum(m)) # 열의 합계
print(np.sum(m))# 집계 합
print(m.sum())
print(np.max(m))
print(m.max())
print(np.min(m))
print(m.min())
print(np.mean(m)) # 전체 평균
print(m.mean())
print(np.std(m)) #표준편차
print(m.std())


[[0.6119504  0.509999   0.7017874 ]
 [0.88348704 0.67331137 0.10021648]
 [0.34144727 0.84984743 0.88748135]
 [0.96977437 0.1016658  0.21359226]]
[2.80665907 2.1348236  1.90307749]
6.844560167144292
6.844560167144292
0.9697743674601365
0.9697743674601365
0.1002164790505985
0.1002164790505985


In [145]:
!pip install pandas


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [146]:
!python.exe -m pip install --upgrade pip

  Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:


ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'c:\\python311\\lib\\site-packages\\pip-23.1.2.dist-info\\AUTHORS.txt'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [151]:
import pandas as pd
df = pd.read_csv("https://github.com/SoongMoo/soldesk20231218")
heights = np.array(df['height(cm)'])
# print(heights) # 배열로 저장
print(height.sum())
print('최소값 :'height.min()) # 0사분위
print('25% :'np.percentile(heights,25))#25 , 1사분위
print('50%(중앙값, 중위값) :'np.percentile(heights,50))#50 , 2사분위
print('50%(중앙값, 중위값) :'np.median(heights))
print('75% :'np.percentile(heights,75)) 3사분위
print(''heights.mean()) # 평균
print(heights.max()) #4사분위
print(heights.std()) # 표준편차

SyntaxError: invalid decimal literal (368661850.py, line 10)

In [6]:
# 시각화
!pip install matplotlib

  Using cached matplotlib-3.8.2-cp311-cp311-win_amd64.whl (7.6 MB)
  Using cached contourpy-1.2.0-cp311-cp311-win_amd64.whl (187 kB)
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)



[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
pip install package_name --user

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
pip install --upgrade pip

  Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'c:\\python311\\lib\\site-packages\\pip-23.1.2.dist-info\\AUTHORS.txt'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [7]:
pip install package_name --user

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import matplotlib.pyplot as plt
plt.hist(heights)

NameError: name 'heights' is not defined

In [169]:
# 팬시 index, 마스크
l = [1,2,3,4,5,6]
#    0 1 2 3 4 5 : index
#   True,False,False True False, False : 팬시 index
print(l[0])
print(l[3])
print(l[True, False, False,True, False ,False])
x = np.array([1,2,3,4,5,6])
print(x)
#[1,2,3,4,5,6]
print(x[0])
print(x[3])
print(x[[True, False ,False,True, False, False]])#마스크
print(x[x > 3])
print(np.sum(x))
print(np.sum([True, False ,False,True, False, False]))# 팬시index의 합계
print(np.sum(x>3))# True의 갯수를 알 수 있다.
#마스크된 전체의 합계
print(x.sum())
print(np.sum(x))
print(x[x>3].sum())
print(np.sum(x[x>3]))


1
4


TypeError: list indices must be integers or slices, not list

In [171]:
print(x >3 )
print(x<3)
print(x<=3)
print(x>=3)
print(x ==3)
print(x!=3) # 팬시 index
print(x[x != 3])#마스크

[False False False]
[ True  True False]
[ True  True  True]
[False False  True]
[False False  True]
[ True  True False]
[1 2]


In [175]:
x1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(x1)
print(x1>5)
print(x1[[[False,False,False],[False,False,True],[True,True,True]]])
print(x1[x1>5])
print(np.sum(x1>5))#True의 갯수
print((x1>5).sum())
print(x1[x1>5].sum())#마스크를 제외한 합계 값

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[6 7 8 9]
4
4
30


In [181]:
rainfall = pd.read_csv("https://raw.githubusercontent.com/SoongMoo/soldesk20231218/main/%EC%B0%B8%EA%B3%A0%EC%9E%90%EB%A3%8C/NumPy/data/Seattle2014.csv")
rainfall['PRCP']
inches = np.array(rainfall['PRCP']/254)
inches
# 0.5인치 이상 온 날은 몇일입니까?
print((inches >= 0.5).sum())
# 0.5인치이상 온 날의 총 강수량은?
print(inches[inches >= 0.5].sum())
# 강수량이 0.5에서 0.8 사이인 날은 몇일이나 되나요?
print(((inches >= 0.5)&(inches <= 0.8)).sum())
# 강수량이 0.5 미만 0.8 초과한 날은?
print((~((inches >= 0.5)&(inches <= 0.8))).sum())
print(((inches < 0.5)|(inches > 0.8)).sum())
#강수량이 0.5미만 0.8초과한 날의 강수량의 합계?
print(inches[~((inches >= 0.5)&(inches <= 0.8))].sum())
print(inches[(inches < 0.5)|(inches > 0.8)].sum())
#비가 안온 날
print((inches == 0).sum())
#비가 온 날
print((inches!=0).sum())

39
30.795275590551178
26
339
339
32.12204724409449
32.12204724409449
215
150


In [9]:
plt.hist(inches, 40)

NameError: name 'plt' is not defined

In [184]:
# 정렬
x = np.array([3,6,2,7,5])
x
print(np.sort(x))
x= np.random.randint(10, size=(4,6))
x
print(np.sort(x , axis =1))
print(np.sort(x , axis =0))
print(np.sort(x))#axis =1

[2 3 5 6 7]
[[1 3 4 6 7 8]
 [0 1 2 5 8 9]
 [0 3 3 4 4 9]
 [0 0 1 4 5 6]]
[[0 0 3 0 2 1]
 [1 3 3 0 4 4]
 [7 4 6 1 8 5]
 [8 5 9 4 9 6]]
[[1 3 4 6 7 8]
 [0 1 2 5 8 9]
 [0 3 3 4 4 9]
 [0 0 1 4 5 6]]


In [188]:
#파티션 나누기 : 작은 값은 왼쪽, 큰 값은 오른쪽으로 배치
#               작은값은 위로, 큰 값은 아래로 배치
print(x)
# 작은 값은 왼쪽 큰값은 오른쪽
print(np.partition(x,3)) # axis = 1 기본값
print(np.partition(x,3,axis = 1))
# 작은 값은 위로, 큰값은 아래로
print(np.partition(x,3,axis = 0)) # 열기준

[[7 4 3 1 8 6]
 [8 5 9 0 2 1]
 [0 3 3 4 9 4]
 [1 0 6 0 4 5]]
[[1 3 4 6 8 7]
 [0 1 2 5 8 9]
 [0 3 3 4 4 9]
 [0 0 1 4 5 6]]
[[1 3 4 6 8 7]
 [0 1 2 5 8 9]
 [0 3 3 4 4 9]
 [0 0 1 4 5 6]]
[[0 3 3 0 2 4]
 [1 0 3 0 4 1]
 [7 4 6 1 8 5]
 [8 5 9 4 9 6]]


In [196]:
df = pd.read_csv("ta_20231226161619.csv")
df
cmax = np.array(df['최고기온(℃)'])
cmax

FileNotFoundError: [Errno 2] No such file or directory: 'ta_20231226161619.csv'