In [1]:
#1.Numpy

In [2]:
import numpy as np

In [3]:
data=[[1,2,3],[4,5,6],[7,8,9]]

a= np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a.dtype  #int

dtype('int32')

In [5]:
type(a)

numpy.ndarray

In [6]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__o

In [11]:
a = a.astype(np.float32) #a = a.astype('float32') 타입 변경
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [12]:
a[0][1]

2.0

In [13]:
a[0]

array([1., 2., 3.], dtype=float32)

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(1,13).reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [18]:
np.nan * 10

nan

In [22]:
a[0][1] = np.nan

In [26]:
import pandas as pd
a = np.random.randint(0,10,24).reshape(4,6)
df = pd.DataFrame(a, index=list("가나다라"), columns=list("ABCDEF"))
df

A  B  C  D  E  F
가  9  3  3  2  4  3
나  3  8  3  4  3  4
다  5  9  8  6  9  3
라  9  6  1  5  5  4

In [27]:
df["A"] #열 만 가능

가    9
나    3
다    5
라    9
Name: A, dtype: int32

In [28]:
df[["B","C","D"]]

B  C  D
가  3  3  2
나  8  3  4
다  9  8  6
라  6  1  5

In [29]:
df.loc["가","A"] # 가행 의 A열 

9

In [31]:
df.loc["가": "다",["A","E"]] # 가,다 행의 A,E열

A  E
가  9  4
나  3  3
다  5  9

In [32]:
df.loc["가": "다",["A","E","E"]] # E행 두번 

A  E  E
가  9  4  4
나  3  3  3
다  5  9  9

In [33]:
df.loc["가": "다"] #  콤마 없이 (행만 사용가능 열은 사용 불가)

A  B  C  D  E  F
가  9  3  3  2  4  3
나  3  8  3  4  3  4
다  5  9  8  6  9  3

In [36]:
df.loc["가": "다","A":"E"] # 행은 가~다 까지 열은 A~E

A  B  C  D  E
가  9  3  3  2  4
나  3  8  3  4  3
다  5  9  8  6  9

In [38]:
df.iloc[0] # 0번째 행인 "가"행이 불러와짐

A    9
B    3
C    3
D    2
E    4
F    3
Name: 가, dtype: int32

In [39]:
df.iloc[0,0] #0번째인 "가"행의 0번째열인 "A"열의 값을 가져옴

9

In [40]:
df.iloc[0:3, 0:5]

A  B  C  D  E
가  9  3  3  2  4
나  3  8  3  4  3
다  5  9  8  6  9

In [41]:
df.iloc[0:3,[1,3]] # 행은 0~3 열은 1번째랑 3번째만

B  D
가  3  2
나  8  4
다  9  6

In [42]:
df. drop( "D",axis=1) # drop 해줘요 "D" 라는 axis=1 열을

A  B  C  E  F
가  9  3  3  4  3
나  3  8  3  3  4
다  5  9  8  9  3
라  9  6  1  5  4

In [51]:
# B,D,E,F열과 가나다행의 자료를 추출
df.iloc[0:3,0:6].drop( ["A","C"],axis=1)

B  D  E  F
가  3  2  4  3
나  8  4  3  4
다  9  6  9  3

In [48]:
# B,D,E,F열과 가나다행의 자료를 추출
df.iloc[:3,1:].drop("C",axis=1)

B  D  E  F
가  3  2  4  3
나  8  4  3  4
다  9  6  9  3

In [54]:
a1 = [60, 84, 80, 70, 19]
a2 = [77, 62, 95, 85, 17]
a3 = [61, 97, 72, 67, 15]
a4 = [75, 65, 95, 51, 18]
cols = ["국어", "영어", "수학", "과학", "나이"]
df = pd.DataFrame([a1, a2, a3, a4], index=list("ABCD"), columns=cols)
df

국어  영어  수학  과학  나이
A  60  84  80  70  19
B  77  62  95  85  17
C  61  97  72  67  15
D  75  65  95  51  18

In [55]:
df.sort_values("국어") #"국어" 성적 기준 오름차순 정렬

국어  영어  수학  과학  나이
A  60  84  80  70  19
C  61  97  72  67  15
D  75  65  95  51  18
B  77  62  95  85  17

In [56]:
df.sort_values("영어",ascending=False) # ascending = 오름차순  ascending =False 는 내림차순

국어  영어  수학  과학  나이
C  61  97  72  67  15
A  60  84  80  70  19
D  75  65  95  51  18
B  77  62  95  85  17

In [58]:
df.sort_values(["수학","영어"],ascending=False) # 수학 내림차순 에서 동점자 끼리는 영어 내림차순

국어  영어  수학  과학  나이
D  75  65  95  51  18
B  77  62  95  85  17
A  60  84  80  70  19
C  61  97  72  67  15

In [59]:
df.sort_values(["수학","나이"],ascending=[0,1]) # 수학 정렬에는 ascending=0(False) 나이에는 ascending =1 (True)을 적용해서
                                               #수학 내림차순 나이 오름차순으로 정렬

국어  영어  수학  과학  나이
B  77  62  95  85  17
D  75  65  95  51  18
A  60  84  80  70  19
C  61  97  72  67  15